#!/usr/bin/env bash
set -euo pipefail
source /home/vscode/.venv/bin/activate
cd "${NUPLAN_DEVKIT_ROOT:-/workspace/nuplan-devkit}"

NUBOARD_FILE="${1:-}"
if [[ -z "${NUBOARD_FILE}" ]]; then
  echo "Pass a .nuboard file generated by a simulation, e.g.:"
  echo "  scripts/run_nuboard.sh /workspace/exp/path/to/file.nuboard"
  echo
  echo "Find nuBoard files with:"
  echo "  find \$NUPLAN_EXP_ROOT -name '*.nuboard' -print"
  exit 2
fi

python nuplan/planning/script/run_nuboard.py \
  simulation_path="${NUBOARD_FILE}" \
  port_number=5006