#!/usr/bin/env python3
"""Demo 07: find and summarize metric artifacts generated by nuPlan runs.

Component demonstrated: Metrics engine.

Run a simulation first, e.g.:
    demos/06_closed_loop_simulation.sh 3

Then run this script.  It searches NUPLAN_EXP_ROOT for metric/nuboard files and
prints a practical summary of what the metrics engine produced.
"""

from __future__ import annotations

import argparse
import json
import pickle
import sys
from pathlib import Path
from typing import Any

from common.nuplan_demo_utils import DEFAULT_EXP_ROOT, ensure_output_dir


def safe_load_pickle(path: Path) -> str:
    try:
        with path.open("rb") as f:
            obj = pickle.load(f)
        return f"pickle type={type(obj).__name__}"
    except Exception as exc:
        return f"pickle unreadable here: {type(exc).__name__}: {exc}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exp-root", type=Path, default=DEFAULT_EXP_ROOT)
    parser.add_argument("--output-dir", type=Path, default=Path("/workspace/nuplan-project/demos/outputs"))
    parser.add_argument("--limit", type=int, default=200)
    args = parser.parse_args()

    if not args.exp_root.exists():
        raise FileNotFoundError(f"Experiment root does not exist: {args.exp_root}")

    interesting_suffixes = {".nuboard", ".json", ".pkl", ".pickle", ".csv", ".parquet"}
    interesting_names = []
    for p in args.exp_root.rglob("*"):
        if not p.is_file():
            continue
        lower_name = p.name.lower()
        if p.suffix.lower() in interesting_suffixes or "metric" in lower_name or "simulation" in lower_name:
            interesting_names.append(p)

    interesting_names = sorted(interesting_names, key=lambda p: p.stat().st_mtime, reverse=True)[: args.limit]

    rows: list[dict[str, Any]] = []
    for p in interesting_names:
        rel = p.relative_to(args.exp_root)
        row: dict[str, Any] = {
            "relative_path": str(rel),
            "size_bytes": p.stat().st_size,
            "suffix": p.suffix,
        }
        if p.suffix.lower() in {".pkl", ".pickle", ".nuboard"}:
            row["inspection"] = safe_load_pickle(p)
        elif p.suffix.lower() == ".json" and p.stat().st_size < 5_000_000:
            try:
                data = json.loads(p.read_text(encoding="utf-8"))
                row["inspection"] = f"json keys={list(data)[:10] if isinstance(data, dict) else type(data).__name__}"
            except Exception as exc:
                row["inspection"] = f"json unreadable: {type(exc).__name__}: {exc}"
        rows.append(row)

    out_dir = ensure_output_dir(args.output_dir)
    out_path = out_dir / "07_metrics_engine_artifacts.json"
    out_path.write_text(json.dumps(rows, indent=2), encoding="utf-8")

    print(f"[demo] experiment root: {args.exp_root}")
    print(f"[demo] interesting metric/simulation/nuBoard artifacts found: {len(rows)}")
    for row in rows[:40]:
        print(f"  {row['relative_path']}  ({row['size_bytes']} bytes)  {row.get('inspection', '')}")
    print(f"[demo] wrote: {out_path}")
    print("[demo] component demonstrated: Metrics engine = YES")
    return 0


if __name__ == "__main__":
    sys.exit(main())
